apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nettest
  template:
    metadata:
      labels:
        app: nettest
    spec:
      containers:
        - name: nettest
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/modernisation-platform/nettest-ecr:1.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
